[pytest]

# Configuration Django
DJANGO_SETTINGS_MODULE = core.settings

# Ajoute le dossier backend dans le chemin Python
pythonpath = backend

# Recherche des fichiers de tests
python_files = test_*.py *_tests.py

# Dossier contenant les applications Django
testpaths = backend

# Options pytest
# -v : affiche plus de détails
# --tb=short : erreurs plus courtes
# --reuse-db : réutilise la base de test
addopts = -v --tb=short --reuse-db

# Affichage de la progression
console_output_style = progress