# Generated by Django 6.0.7 on 2026-07-21 03:15

from django.db import migrations


from django.db import migrations

def create_initial_data(apps, schema_editor):
    Category = apps.get_model('services', 'Category')
    Product = apps.get_model('services', 'Product')

    # Création des catégories
    categories = {
        'Web': 'Conception de Sites Web',
        'Logiciel': 'Logiciels de Bureau',
        'Mobile': 'Applications Mobiles',
        'Forage': 'Forage et Hydraulique',
        'Boutique': 'Boutique en ligne',
    }

    created_categories = {}
    for slug, name in categories.items():
        cat = Category.objects.create(name=name, slug=slug.lower())
        created_categories[slug] = cat

    # Services de base par défaut (exemples)
    Product.objects.create(
        name="Site Web Vitrine",
        description="Site professionnel simple",
        price=150000,
        category=created_categories['Web'],
        is_service=True
    )
    Product.objects.create(
        name="Forage Standard",
        description="Forage d'eau avec installation pompe",
        price=500000,
        category=created_categories['Forage'],
        is_service=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
