# Generated by Django 6.0.7 on 2026-07-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, verbose_name="Page visitée")),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "Visite de page",
                "verbose_name_plural": "Visites de page",
                "ordering": ["-visited_at"],
            },
        ),
    ]
