# Generated by Django 6.0.7 on 2026-07-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_pagevisit"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(max_length=500, unique=True)),
                ("p256dh", models.CharField(max_length=200)),
                ("auth", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Abonnement notification",
                "verbose_name_plural": "Abonnements notifications",
            },
        ),
    ]
